### ISSUE TITLE
VeilLayout doesn't work as expected in RecyclerView

### ISSUE THREAD

**Issue by sieunju** [skydoves/AndroidVeil#24]
조건은 RecyclerView 와 DiffUtil 를 사용하고 있고요.
안에 ViewHolder 안에 VeilLayout 사용하고 있습니다.
대충 구조는
RecyclerView
-> ViewHolder
   -> VeilLayout

한번 veil 호출하고 몇초뒤 unveil 호출 했습니다. (정상 동작 O)
이후 veil 재호출하면 제대로 동작이 안될때 있고 될때가 있습니다... 

왜 안되는지 알수 있을까요??

**Comment by skydoves** [comment]
Hey @sieunju,
sorry for the late response. If you need to use `VeilLayout` in your RecyclerView, it'd be very complicated, because each `VeilLayout` has its independent status. So their behavior might be different from your expectations. For this case, I'd highly recommend using `VeilRecyclerFrameView` instead. Thanks!

**Comment by sieunju** [comment]
Oh! I understood. Thanks @skydoves
