### ISSUE TITLE
Delay in showing the shimmer effect

### ISSUE THREAD

**Issue by mak3ru-in0ch1** [skydoves/AndroidVeil#7]
- Library Version 1.0.6
- Affected Device(s) All

I just started using this dependency but I have encountered a serious problem. **Why do I have this great delay to show the shimmer effect in the recyclerview?** It takes a **long time for the effect to appear**.

I attach screen with the problem (I'm sorry for the poor quality, just so I could convert the video to gif).
![Screenrecorder-2019-10-31-10-55-57-356_0_](https://user-images.githubusercontent.com/56084970/67969571-2ccdd600-fbcf-11e9-968b-d0c2cb115ab0.gif)

Any way to solve this? Just in case it is necessary to know, **I do the unVeil() only when I get all the data of my api on the internet**.

**Comment by skydoves** [comment]
@mak3ru-in0ch1 
Hi,

I recommend to use the view's default visibility to `invisible`, and make it to `visible` after called `unveil`. like below.
[Usecase0-Layout](https://github.com/skydoves/AndroidVeil/blob/master/app/src/main/java/com/skydoves/androidveildemo/DetailActivity.kt).
[Usecase1-RecyclerView](https://github.com/skydoves/AndroidVeil/blob/master/app/src/main/java/com/skydoves/androidveildemo/profile/ProfileViewHolder.kt) and [layout-xml](https://github.com/skydoves/AndroidVeil/blob/master/app/src/main/res/layout/item_profile.xml).

The `veil` function will wait during the masking all of the views, because of measuring the size of views.
Some people or companies do not want all of the views being `invisible` and using `veil` firstly, so I did not make the views `invisible` as the basic works.

Thank you for your issue!

**Comment by skydoves** [comment]
@mak3ru-in0ch1 

It is added a new feature #8.
Implemented a new feature: `defaultChildVisible`.
All child views will be invisibled when called `veil()` by default.
This feature will be applied on the next version !

**Comment by mak3ru-in0ch1** [comment]
Great. :)

**Comment by mak3ru-in0ch1** [comment]
Thanks You.
